export type Project = {
  id: number;
  company: string;
  project: string;
  year: number;
  client: string;
};

export const PROJECTS_DATA: Project[] = [
  {
    id: 1,
    company: "ALMOE DIGITAL SOLUTIONS L.L.C",
    project: 'SAMSUNG 86" SMART BOARD AND ALUMINUM CABINET FOR 520 CLASSROOMS',
    year: 2015,
    client: "MINISTRY OF EDUCATION",
  },
  {
    id: 2,
    company: "GECO ELECTRO-MECHANICAL L.L.C",
    project: "ELV WORKS",
    year: 2015,
    client: "AL TAYER GARHOUD",
  },
  {
    id: 3,
    company: "ALMOE DIGITAL SOLUTIONS L.L.C",
    project: 'SAMSUNG 82" SMART BOARD AND ALUMINUM CABINET FOR 983 CLASSROOMS',
    year: 2016,
    client: "MINISTRY OF EDUCATION",
  },
  {
    id: 4,
    company: "GECO ELECTRO-MECHANICAL L.L.C",
    project: "ELV WORKS",
    year: 2016,
    client: "SAHARA MALL SHARJAH",
  },
  {
    id: 5,
    company: "ALMOE DIGITAL SOLUTIONS L.L.C",
    project: 'SPECKTRON 86" SMART BOARD AND ALUMINUM CABINET FOR 1350 CLASSROOMS',
    year: 2017,
    client: "MINISTRY OF EDUCATION",
  },
  {
    id: 6,
    company: "ALMOE DIGITAL SOLUTIONS L.L.C",
    project: "EPSON EB710UI DATASHOW AND WHITEBOARD 3529 CLASSROOMS",
    year: 2019,
    client: "MINISTRY OF EDUCATION",
  },
  
 
  {
    id: 9,
    company: "ALMOE DIGITAL SOLUTIONS L.L.C",
    project: "EPSON EB710UI & EB1485FI DATASHOW AND WHITEBOARD 1371 CLASSROOMS",
    year: 2022,
    client: "MINISTRY OF EDUCATION",
  },
  
  {
    id: 11,
    company: "VOLTAS-SIX CONSTRUCT JOINT VENTURE",
    project: "ELV WORKS",
    year: 2022,
    client: "UPTOWN TOWER",
  },
  {
    id: 12,
    company: "KHANSAHEB MEP",
    project: "ELV WORKS",
    year: 2022,
    client: "BAB AL SHAMS RESORT",
  },
  {
    id: 13,
    company: "ALMOE DIGITAL SOLUTIONS L.L.C",
    project: "EPSON EB1481FI DATASHOW AND WHITEBOARD 110 CLASSROOMS",
    year: 2023,
    client: "MINISTRY OF EDUCATION",
  },
  {
    id: 14,
    company: "PROJECTION HOUSE L.L.C",
    project: 'SPECKTRON 75" SMART BOARD FOR 45 CLASSROOMS',
    year: 2023,
    client: "DWIGHT SCHOOL DUBAI",
  },
  {
    id: 15,
    company: "ALMOE RENTAL L.L.C",
    project: "BOSE AUDIO SYSTEM",
    year: 2023,
    client: "AL HABTOOR HORSE RACE AL BARSHA",
  },
  {
    id: 16,
    company: "KHANSAHEB MEP",
    project: "ELV WORKS",
    year: 2023,
    client: "EXPO CITY - THE THEMATIC DISTRICT TRANSITION",
  },
  {
    id: 17,
    company: "ALMOE DIGITAL SOLUTIONS L.L.C",
    project: "EPSON EB1481FI DATASHOW AND WHITEBOARD 2542 CLASSROOMS",
    year: 2024,
    client: "MINISTRY OF EDUCATION",
  },
  {
    id: 18,
    company: "ABSONS IT SOLUTIONS & EQUIPMENT",
    project: "LED WALL CURVED, L SHAPE, PILLER TYPE, SQUARE TYPE",
    year: 2024,
    client: "MYDON HUDAIRIYAT ISLAND ABUDHABI",
  },
  {
    id: 19,
    company: "ABSONS IT SOLUTIONS & EQUIPMENT",
    project: "LED WALL",
    year: 2024,
    client: "YAS MALL ABUDHABI",
  },
  {
    id: 20,
    company: "ABSONS IT SOLUTIONS & EQUIPMENT",
    project: "LED WALL",
    year: 2024,
    client: "FERRARI WORLD AUH",
  },
  {
    id: 21,
    company: "ALPHADATA",
    project: "AV SYSTEM",
    year: 2024,
    client: "KHAZNA",
  },
  {
    id: 22,
    company: "SIBCA",
    project: "AV SYSTEM",
    year: 2024,
    client: "BLUE WATER",
  },
  {
    id: 23,
    company: "JAMES L WILLIAMS",
    project: "ELV WORKS",
    year: 2024,
    client: "SHARJAH AIRPORT",
  },
 
 
  {
    id: 26,
    company: "ALMOE DIGITAL SOLUTIONS L.L.C",
    project: "LED WALL",
    year: 2024,
    client: "GITEX EVENT",
  },
  {
    id: 27,
    company: "NMK ELECTRONINCS",
    project: "LED WALL",
    year: 2024,
    client: "GITEX EVENT",
  },
  {
    id: 28,
    company: "AVIENTEK ELECTRONINCS",
    project: "LED WALL",
    year: 2024,
    client: "GITEX EVENT",
  },
  {
    id: 29,
    company: "ABCOM DISTRIBUTION LLC",
    project: "LED WALL",
    year: 2024,
    client: "GITEX EVENT",
  },
  {
    id: 30,
    company: "VOGO HOTELS",
    project: "AV SYSTEM",
    year: 2024,
    client: "ABU DHABI GOLF CLUB",
  },
  {
    id: 31,
    company: "ABSONS IT SOLUTIONS & EQUIPMENT",
    project: "LED WALL",
    year: 2025,
    client: "GARDEN PLAZA",
  },
  {
    id: 32,
    company: "SIBCA",
    project: "AV SYSTEM",
    year: 2025,
    client: "BAECH MANSION",
  },
  {
    id: 33,
    company: "SIBCA",
    project: "AV SYSTEM",
    year: 2025,
    client: "DEWA",
  },
  {
    id: 34,
    company: "SIBCA",
    project: "AV SYSTEM",
    year: 2025,
    client: "DISTRIC COOL PLANT",
  },
  {
    id: 35,
    company: "SIBCA",
    project: "AV SYSTEM",
    year: 2025,
    client: "CITY TOWER",
  },
  {
    id: 36,
    company: "ALPHADATA",
    project: "AV SYSTEM",
    year: 2025,
    client: "UNIVERSITY OF SHARJAH",
  },
  {
    id: 37,
    company: "AVIENTEK",
    project: "AV SYSTEM",
    year: 2025,
    client: "ZAYED MILITARY CITY - AUH",
  },
  {
    id: 38,
    company: "ABSONS IT SOLUTIONS & EQUIPMENT",
    project: "LED WALL",
    year: 2025,
    client: "MODON - AUH",
  },
  {
    id: 39,
    company: "ALMOE DIGITAL SOLUTIONS L.L.C",
    project: "BGM SYSTEM",
    year: 2025,
    client: "BURJUMAN CENTRE",
  },
];
